# Generated by Django 2.1 on 2019-12-22 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoria')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'Categoria de Historia',
                'verbose_name_plural': 'Categoria de Historias',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Historia')),
                ('fecha_inicio', models.DateField(null=True, verbose_name='Fecha Inicio')),
                ('fecha_termino', models.DateField(null=True, verbose_name='Fecha Termino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Categoria_Historia')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
            },
        ),
        migrations.RemoveField(
            model_name='trama',
            name='escenario',
        ),
        migrations.AlterField(
            model_name='etapa',
            name='trama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Historia'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='trama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaje_set', to='core.Historia', verbose_name='trama'),
        ),
        migrations.AlterField(
            model_name='texto',
            name='trama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Historia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personaje',
            field=models.ManyToManyField(related_name='personajes', through='core.Personaje', to='core.Historia'),
        ),
        migrations.DeleteModel(
            name='Escenario',
        ),
        migrations.DeleteModel(
            name='Trama',
        ),
    ]
