# Generated by Django 2.1 on 2019-12-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191222_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapa',
            old_name='trama',
            new_name='historia',
        ),
        migrations.RenameField(
            model_name='historia',
            old_name='escenario',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='texto',
            old_name='trama',
            new_name='historia',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='trama',
        ),
        migrations.AddField(
            model_name='personaje',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personaje_set', to='core.Historia', verbose_name='historia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria_historia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
