# Generated by Django 2.1 on 2019-12-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191222_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
