# Generated by Django 2.1 on 2020-01-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historia_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='nombre',
            field=models.TextField(default=1, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
