# Generated by Django 2.1 on 2020-01-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pregunta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
