# Generated by Django 2.1.4 on 2018-12-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Contexto')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escenario.Escenario')),
            ],
        ),
    ]
