# Generated by Django 2.1.4 on 2018-12-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0003_textos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Textos',
            new_name='Texto',
        ),
    ]
