# Generated by Django 2.1.4 on 2018-12-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0004_auto_20181229_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Trama')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escenario.Escenario')),
            ],
        ),
        migrations.RemoveField(
            model_name='contexto',
            name='escenario',
        ),
        migrations.AlterField(
            model_name='texto',
            name='contexto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escenario.Trama'),
        ),
        migrations.DeleteModel(
            name='Contexto',
        ),
    ]
