# Generated by Django 2.1.4 on 2018-12-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0005_auto_20181229_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Contexto')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escenario.Escenario')),
            ],
        ),
        migrations.RemoveField(
            model_name='trama',
            name='escenario',
        ),
        migrations.AlterField(
            model_name='texto',
            name='contexto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escenario.Contexto'),
        ),
        migrations.DeleteModel(
            name='Trama',
        ),
    ]
