# Generated by Django 2.1.4 on 2018-12-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0007_auto_20181229_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='trama',
            name='fin',
            field=models.DateField(null=True, verbose_name='Fecha Termino'),
        ),
        migrations.AddField(
            model_name='trama',
            name='inicio',
            field=models.DateField(null=True, verbose_name='Fecha Inicio'),
        ),
    ]
