# Generated by Django 2.1.4 on 2018-12-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0008_auto_20181229_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Evento')),
                ('trama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escenario.Trama')),
            ],
        ),
    ]
