# Generated by Django 2.1.4 on 2018-12-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0011_etapas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etapas',
            new_name='Etapa',
        ),
    ]
