# Generated by Django 2.1.4 on 2018-12-30 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0012_auto_20181229_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texto',
            old_name='contexto',
            new_name='trama',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='trama',
        ),
        migrations.AddField(
            model_name='evento',
            name='etapa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='escenario.Etapa'),
        ),
    ]
