# Generated by Django 2.1.4 on 2018-12-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0013_auto_20181229_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escenario.Etapa'),
        ),
    ]
