# Generated by Django 2.1.4 on 2018-12-30 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0014_auto_20181229_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escenario.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escenario.Tipo_Pregunta'),
        ),
    ]
