# Generated by Django 2.1.4 on 2018-12-30 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0015_auto_20181229_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escenario.Etapa'),
        ),
    ]
