# Generated by Django 2.1.4 on 2018-12-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0016_pregunta_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones_Pegunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.ManyToManyField(to='escenario.Opciones_Pegunta'),
        ),
    ]
