# Generated by Django 2.1.4 on 2018-12-30 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0017_auto_20181229_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones_pegunta',
            name='trama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='escenario.Trama'),
        ),
    ]
