# Generated by Django 2.1.4 on 2018-12-30 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0018_opciones_pegunta_trama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opciones_pegunta',
            name='trama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escenario.Trama'),
        ),
    ]
