# Generated by Django 2.1.4 on 2018-12-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escenario', '0019_auto_20181229_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='etapa',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='etapa',
            field=models.ManyToManyField(blank=True, null=True, to='escenario.Etapa'),
        ),
    ]
